#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X   
bspc config border_width        4 
bspc config window_gap         4

#bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# Border
bspc config focused_border_color        "#0771ed"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

# Autostart
picom  &
# notifications 
dunst &
# Polybar
~/.config/polybar/launch.sh &
# Polkit
/usr/libexec/polkit-gnome-authentication-agent-1 &
# Redshift
redshift-gtk &
# Wallpaper
nitrogen --restore &
# Dex
dex-autostart -a -s /etc/xdg/autostart/:~/.config/autostart/ &
setxkbmap -option 'grp:alt_space_toggle' & 
xsetroot -cursor_name left_ptr 
#Rules
bspc rule -a firefox  desktop=II 
bspc rule -a discord   desktop=III 
bspc rule -a TelegramDesktop  desktop=III 
bspc rule -a Pcmanfm desktop=V
bspc rule -a steamwebhelper desktop=VII
bspc rule -a Galculator state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Zathura state=tiled
