# [theme]
# theme = "modern"

[icons]
icons = "material-nf"
[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a, %d %b %y %R')" 

# [[block]]
# block = "keyboard_layout"
# driver ="localebus"
[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "$icon $available.eng(w:2)"
[[block]]
block = "dnf"
interval = 1800
format = " $icon $count.eng(w:1)"
format_singular = " $icon One update available "
format_up_to_date = " $icon system up to date "
critical_updates_regex = "(linux|linux-lts|linux-zen)"

[[block]]
block = "memory"
format = "$icon $mem_avail.eng(prefix:M)/$mem_total.eng(prefix:M)"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"
max_vol=100


