 [theme]
 theme = "modern"

[icons]
icons = "material-nf"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20) $play $next |}"
player = "spotify"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a, %d %b %y| %T')" 


[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "$icon $available.eng(w:2)"

[[block]]
block = "memory"
interval = 10
warning_mem = 70
critical_mem = 90
format = "$icon $mem_used.eng(prefix:M)/$mem_total.eng(prefix:M)"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
format = "$icon $max"
interval = 1
chip = "k10temp-pci-00c3"
[[block]]
block = "sound"
max_vol=100


