theme = "bad-wolf"
icons = "awesome5"

[[block]]
block = "keyboard_layout"
driver = "kbddbus"
[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "{icon} {available}"
[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
clickable = false
[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"
max_vol=100
[[block]]
block = "time"
interval = 1
format = "%a %d %b %H:%M:%S"
locale = "ru_RU"
[[block]]
block = "net"
device = "enp4s0"
format = "{speed_down;K*b}"
interval = 5
[[block]]
block = "custom"
command = "echo \uf011" # assumes fontawesome icons
on_click = "~/.config/rofi/powermenu.sh"
interval = "once"
