#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X   
bspc config border_width        4 
bspc config window_gap         4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# Border
bspc config focused_border_color        "#0771ed"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"
#Rules
bspc rule -a Firefox desktop='^2'
bspc rule -a Discord desktop='^3'
bspc rule -a Telegram desktop='^3'
bspc rule -a Thunderbird desktop='^4'
bspc rule -a Pcmanfm desktop='^5'
bspc rule -a Spotufy  desktop='^6'
bspc rule -a Steam desktop='^7'
bspc rule -a Galculator state=floating
bspc rule -a Pavucontrol state=floating
# Autostart

# Polybar
~/.config/polybar/launch.sh &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Redshift
redshift-gtk &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/ &
