[colors]

fg-blue = #5294e2
focus-dark = #1b2124
blue = #73d0ff
blue-darker = #0771ed
green = #bae67e
dark-green = #75c933
red = #ff3333
bg = #cc000000
fg = #bfbab0
cyan = #95e6cb
alpha = #00000000
white = #fff

[bar/top]
;monitor =HDMI-0

override-redirect = false

; Put the bar at the bottom of the screen
bottom = false

; Prefer fixed center position for the `modules-center` block
fixed-center = true

width = 100%
height = 29

offset-x = 
offset-y =  

; Background ARGB color (e.g. #f00, #ff992a, #ddff1023)
background = ${colors.bg}

; Foreground ARGB color (e.g. #f00, #ff992a, #ddff1023)
foreground = ${colors.fg}

line-size = 0
line-color = #fff

; Number of spaces to add at the beginning/end of the bar
; Individual side values can be defined using:
;   padding-{left,right}
padding-right = 1 
padding-left = 0

; Number of spaces to add before/after each module
; Individual side values can be defined using:
;   module-margin-{left,right}
module-margin = 0
font-0 = "UbuntuMono Nerd Font:size=10;2"
font-1 = "UbuntuMono Nerd Font:size=10;2"

modules-left =  bspwm
modules-center = date
modules-right = xkeyboard spc filesystem spc pulseaudio spc memory spc cpu spc wired-network spc powermenu

separator =

dim-value = 1.0

wm-name =
tray-position = right

tray-detached = false

tray-maxsize = 24

tray-background =${colors.bg}
;offset defined as pixel value (e.g. 35) or percentage (e.g. 50%)

tray-padding = 2

tray-scale = 1

wm-restack = bspwm

dpi-x = 133
dpi-y = 133

enable-ipc = false

border-color = ${colors.alpha}

[module/bspwm]
type = internal/bspwm

pin-workspaces = true

inline-mode = false

enable-click = true

enable-scroll = true

reverse-scroll = false

fuzzy-match = true

ws-icon-0 = "I;%{T1}		%{T-}"
ws-icon-1 = "II;%{T1}		 %{T-}"
ws-icon-2 = "III;%{T1}	ﮠ	 %{T-}"
ws-icon-3 = "IV;%{T1} 4 %{T-}"
ws-icon-4 = "V;%{T1}  %{T-}"
ws-icon-5 = "VI;%{T1}		 %{T-}"
ws-icon-6 = "VII;%{T1}		 %{T-}"
ws-icon-7 = "VIII;%{T1} 8 %{T-}"
ws-icon-8 = "IX;%{T1} 9 %{T-}"
ws-icon-9 = "X;%{T1} 10 %{T-}"
format = <label-state> <label-mode>

label-monitor = %name%

label-dimmed-foreground = #555
label-dimmed-underline = ${bar/top.background}
label-dimmed-focused-background = #f00

label-focused = %icon%
label-focused-foreground = ${colors.focus-dark}
label-focused-background = ${colors.fg-blue}
label-focused-underline = #fba922

label-occupied = %icon%
label-occupied-padding = 0
label-occupied-foreground = ${colors.fg-blue}

label-urgent = %icon%
label-urgent-foreground = ${colors.red}

label-empty = %icon%
label-empty-foreground = #55
label-empty-padding = 0

; Separator in between workspaces
label-separator =
label-separator-padding = 0
label-separator-foreground = #ffb52a

[module/date]
type = internal/date

; Seconds to sleep between updates
interval = 1.0

date =%{T1} %a, %d %b %y%{T-}

; Optional time format
time =%{T2} %H:%M:%S%{T-}

label = %date%%time%
label-font = 0
label-foreground = ${colors.white}

[module/cpu]
type = internal/cpu

interval = 0.5

label = %{T1}%{T-}%{T2} %percentage:2%%%{T-}

label-foreground = ${colors.white}

[module/memory]
type = internal/memory

interval = 0.5
format = <label>

label = %{T1}%{T-}%{T2} %gb_used%%{T-}

label-foreground = ${colors.white}

[module/spc]
type = custom/text
content = " "
content-padding = 0

[module/title]
type = internal/xwindow
format = <label>
format-background = ${colors.bg}
format-foreground = ${colors.white}
format-padding = 4

label = "%{T1}类%{T-}%{T2} %title%%{T-}"
label-maxlen = 65

label-empty =%{T2}Arch Linux%{T-}
label-empty-foreground = #707880

[module/pulseaudio]
type = internal/pulseaudio

use-ui-max = false

interval = 5
format-volume = <label-volume>

format-muted = <label-muted>

label-volume = %{T1}墳%{T-} %{T2}%percentage%%%{T-}
label-volume-foreground = ${colors.white}

label-muted = %{T1}ﱝ%{T-} %{T2}shhh!%{T-}
label-muted-foreground = ${colors.red}

ramp-volume-0 = %{T1}%{T-}
ramp-volume-1 = %{T1}%{T-}
ramp-volume-2 = %{T1}%{T-}

; Right and Middle click (unreleased)
click-right = pavucontrol &
; click-middle =

[module/powermenu]
type = custom/text
content = "襤"
click-left = ~/.config/rofi/powermenu.sh
content-background = ${colors.bg}
content-foreground = ${colors.white}
content-padding = 1
margin-right = 0
[module/filesystem]
type = internal/fs

; Mountpoints to display
mount-0 = /
format-mounted =  <label-mounted>
label-mounted =  %free% 
label-mounted-foreground=${colors.white}
interval = 10

fixed-values = false
spacing = 4

[module/wired-network]
type = internal/network
interface = enp4s0
label-connected = 
label-connected-foreground = ${colors.white}
label-disconnected=
label-disconnected-foreground =${colors.red}

[module/xkeyboard]
type = internal/xkeyboard
label-layout-background =${colors.bg}
label-layout-foreground = ${colors.white}
; List of indicators to ignore
blacklist-0 = num lock
blacklist-1 = scroll lock
